name: Carpentry
on:
  push:
    branches:
      - main
  pull_request:
env:
  IMAGE_NAME: arcaflow-plugin-fio
  IMAGE_TAG: 'latest'
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  carpenter-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: carpenter build
        uses: arcalot/arcaflow-plugin-image-builder
        with:
          args: build --build --push